### ISSUE TITLE
ENVKEY invalid with freshly generated server key

### ISSUE THREAD

**Issue by collingo** [envkey/envkey-node#1]
Thanks for building this amazingly useful tool and service. It will speed up our work no end and be invaluable as we scale.

I am unfortunately getting an error when attempting to use a freshly generated server key (locally everything seems to work fine).

```
/usr/src/node_modules/envkey/loader.js:52
  throw "ENVKEY invalid. Couldn't load vars."
  ^
ENVKEY invalid. Couldn't load vars.
```

I have confirmed that the `ENVKEY` is being set correctly on the environment and, after reading through the code in [`loader.js`](loader.js), it looks like the error is thrown [in this try catch block](https://github.com/envkey/envkey-node/blob/master/loader.js#L163) where the key has been found on the environment but is getting some negative response from the server.

```
try {
  var res = execFileSync(filePath, execArgs).toString()
  if(!res || !res.trim())throwKeyError()
  var json = JSON.parse(res.toString())
  if(!json || typeof json == "string")throwKeyError()
  return pickPermitted(json, opts)
} catch (e){
  throwKeyError()
}
```

It's not clear which of the `throwKeyError`s are being triggered from the logs so any help would be appreciated :) Have I configured something incorrectly to be getting this `INVALID` response?

I should add I am running this inside a Docker container with a base image of `node:6.11.3-alpine`. Are the envkey executables expecting any external libraries as they may not be installed in this slimmed down alpine instance?

**Comment by danenania** [comment]
Hi, thanks for the detailed bug report. The executables are statically compiled with no dependencies, so there shouldn't be an issue on Alpine, but I will do some testing with that container to see what's up.

**Comment by collingo** [comment]
Thanks @danenania - let me know if you need any further details

**Comment by collingo** [comment]
I did some further investigation. I was actually running two different docker images - one for local development, which was working, and a leaner build for production. After a bit of divide and conquer debugging on the Dockerfiles I've narrowed it down to the installation of `git` on the development image that seem to make things work. Since I am using `apk` (alpine's package repository) installing git also installs the following binaries...

```
(1/6) Installing ca-certificates (20161130-r0)
(2/6) Installing libssh2 (1.7.0-r0)
(3/6) Installing libcurl (7.55.0-r0)
(4/6) Installing expat (2.2.0-r1)
(5/6) Installing pcre (8.38-r1)
(6/6) Installing git (2.8.6-r0)
```

I'm presuming one, or a combination of the above, are needed to get EnvKey working in an alpine based image. I'll continue narrowing down this list for now as it would surprise me if `git` was a direct dependency of the executables 😁

**Comment by collingo** [comment]
Finally narrowed it down to this package - `ca-certificates`. For anyone else reading this it was resolved by adding the following to the Dockerfile...

`RUN apk add --no-cache ca-certificates`

Closing for now. Thanks for your help @danenania

**Comment by danenania** [comment]
Great, glad you were able to track it down @collingo!
