### ISSUE TITLE
error: ENVKEY invalid

### ISSUE THREAD

**Issue by mkulgeorge** [envkey/envkey-node#15]
Hello Team,

I just followed the 2 simple steps mentioned in the document.
1. download the node js package
2. write the import statement
3. I used the demo org to setup a password and added that to the .env file 
Here is the js code

```

const envkey = require('envkey');
console.log('Key ' , process.env);

```

when i execute the js program i get the below error

```
error: ENVKEY invalid
error: ENVKEY invalid


C:\Users\userid\node_modules\envkey\loader.js:216
      throw(e.stderr.toString())
      ^
error: ENVKEY invalid
```

This happens both in Windows 7 and Ubuntu 14.04

Am i missing something?

Thanks,
George.

**Comment by danenania** [comment]
Hi George,

Could you send a quick email to support@envkey.com with your account's email address so I can take a look from the back end to see if anything jumps out?

Also, a few troubleshooting questions:

- Can you curl `https://env.envkey.com/health` from wherever your app is running?
- Does `process.env.ENVKEY` match the `ENVKEY` you have set in your .env file?
- Does the `ENVKEY` match the format `[20 character string]-[16 character string]`? Sometimes when copying/moving these around, characters can get accidentally clipped off.
- If all of the above are ok, can you try to curl `https://env.envkey.com/v1/[envkey-id-part]`--the envkey-id-part being the first 20 characters of the `ENVKEY` (before the hyphen)--and check if you get a successful response?
