### ISSUE TITLE
Certificate signed by unknown authority

### ISSUE THREAD

**Issue by kevintc** [envkey/envkey-node#17]
Hello,

When testing locally and on our CI (TravisCI), envkey worked well.
But when taking it to our development server, we have the following error :
```bash
error: could not load from server or s3 backup.
fetch error: Get https://env.envkey.com/v1/***key***?clientName=envkey-node&clientVersion=1.2.6&clientOs=linux&clientArch=amd64: x509: certificate signed by unknown authority
backup fetch error: 2 errors occurred:
	* Get https://me66hg5t17.execute-api.eu-west-1.amazonaws.com/default/envBackup?v=1&id=***key***&clientName=envkey-node&clientVersion=1.2.6&clientOs=linux&clientArch=amd64: x509: certificate signed by unknown authority
	* Get https://s3-eu-west-1.amazonaws.com/envkey-backup/envs/v1/***key***?clientName=envkey-node&clientVersion=1.2.6&clientOs=linux&clientArch=amd64: x509: certificate signed by unknown authority
```

This message pops in our `docker logs` as an infinite loop at the start of our API.

Do you know how we could solve that ? Or where to look for a solution ?

Thank you :)

**Comment by danenania** [comment]
Hi! Can you try adding the `ca-certificates` dependency to your `Dockerfile` and see if that helps?

**Comment by kevintc** [comment]
`RUN apk add --no-cache ca-certificates` seems to do the trick. Installed it in the container and it looks better, thanks :) I will finish it tomorrow and keep you in touch :)

**Comment by danenania** [comment]
Great @kevintc !

**Comment by kevintc** [comment]
It would probably be nice to add a little note about this issue in the readme :)

**Comment by danenania** [comment]
@kevintc good call--done!
