### ISSUE TITLE
Can we override variables in a .env.test file?

### ISSUE THREAD

**Issue by shamoons** [envkey/envkey-node#19]
I know anything in `.env` will override. But what about `.env.test`?

**Comment by danenania** [comment]
Yes, with [custom loading](https://github.com/envkey/envkey-node#custom-loading) you can specify a different path:

```javascript
import {load as envkeyLoad} from 'envkey/loader'

envkeyLoad({ dotEnvFile: ".staging.env" })
```

**Comment by shamoons** [comment]
Then do I need to have a `.env.test` file? Or will it also work from actual environment variables @danenania ?

**Comment by danenania** [comment]
envkey will defer to anything in the `.env` file (which could be `.env.test` or whatever path you set) _or_ any environment variables that are already set. So either would work to override.
