### ISSUE TITLE
1.1.0 breaks

### ISSUE THREAD

**Issue by selfagency** [envkey/envkey-node#2]
after i upgraded to the latest available release in yarn i started getting:

```
    >> /Users/daniel/Dev/nylon-web/node_modules/envkey/loader.js:53
    >>   throw "ENVKEY invalid. Couldn't load vars."
    >>   ^
    >> ENVKEY invalid. Couldn't load vars.
```

**Comment by danenania** [comment]
Looking into it.

**Comment by danenania** [comment]
Can you let me know if 1.1.1 solves the issue? Thanks!

**Comment by selfagency** [comment]
seems to work now, will let you know if the issue resurfaces

**Comment by selfagency** [comment]
still happening 
```
    [nodemon] child pid: 5970
    >> /Users/daniel/Dev/nylon-web/node_modules/envkey/loader.js:52
    >>   throw "ENVKEY invalid. Couldn't load vars."
    >>   ^
    >> ENVKEY invalid. Couldn't load vars.
    [nodemon] app crashed - waiting for file changes before starting...
```

but this was just happening on 1.0.0 so i'm wondering if you're having connectivity problems

**Comment by danenania** [comment]
Gotcha - 1.1.1 fixes an issue that was preventing failover to S3 from working correctly, so you shouldn't see anymore problems after upgrading. Let me know if you do.
