### ISSUE TITLE
Seems to break with TypeScript when built

### ISSUE THREAD

**Issue by shamoons** [envkey/envkey-node#20]
I think it's because the built JS doesn't include `envkey` at the top. Any way around this?

**Comment by danenania** [comment]
@shamoons looking into this

**Comment by danenania** [comment]
Perhaps it could be due to an unused import getting stripped out at some point, either by TypesScript or at another stage of your build? If you use a `require` instead of an `import` does that help?

**Comment by danenania** [comment]
@shamoons any luck with this? Closing for now but will re-open if it's still unresolved.
