### ISSUE TITLE
Unable to use absolute file paths with envkey/loader

### ISSUE THREAD

**Issue by elsbree** [envkey/envkey-node#21]
We have a use case where our app has several different app.js files, each in separate directories, that import our envkey configuration. When using envkey/loader to point to our .env file, the location of the .env file is always relative to the location of the app.js file that is being run because `./` is always prepended to `opts.dotEnvFile` [here](https://github.com/envkey/envkey-node/blob/master/loader.js#L40).

I've submitted a PR that only prepends `./` to `opts.dotEnvFile` if the first character of `opts.dotEnvFile` is NOT a slash. This allows us to provide an absolute path to the .env file, and should not interfere with any existing configurations that use relative paths.

**Comment by danenania** [comment]
Thanks @elsbree, looks good! We'll merge/release soon.

**Comment by danenania** [comment]
Now merged and released in 1.2.8
