### ISSUE TITLE
CLI version

### ISSUE THREAD

**Issue by magne4000** [envkey/envkey-node#23]
I would like to be able to invoke `envkey` directly from my `package.json` scripts.
One of my use case is to be able to invoke [prisma](https://www.prisma.io/) cli, which needs some env vars.

**Comment by danenania** [comment]
Hey, check out [envkey-source](https://github.com/envkey/envkey-source)--it's designed for exactly this kind of use case.

**Comment by magne4000** [comment]
Great! Thanks!
