### ISSUE TITLE
Apple Mac Silicon Issue 

### ISSUE THREAD

**Issue by andrewphillipo** [envkey/envkey-node#24]
Hello, 

I think amd64 works on M1 macs and should be selected instead of 386 which causes the following error:

    spawnSync /Users/..../project/node_modules/envkey/ext/envkey-fetch_1.2.5_darwin_386/envkey-fetch Unknown system error -86

I can do you a PR to fix this, but for now I'm just editing the 386 envkey-fetch to be the amd64 version:

You can edit this here:

https://github.com/envkey/envkey-node/blob/36f1f999b2fc4701120a90b132715d7b7c61b599/loader.js#L175

And add the following on the line above:

```
case 'arm64':
```

Cheers!

**Comment by danenania** [comment]
Thanks Andrew! I'll get this merged and released.

**Comment by andrewphillipo** [comment]
Ah I ended up creating the PR.
