### ISSUE TITLE
Adopt `envkey` to `next.js`

### ISSUE THREAD

**Issue by vespaiach** [envkey/envkey-node#26]
I'm using `envkey` for my web app which is using `next.js`, and I find the only way to adopt `envkey` is to custom a server page and import `envkey` lib there (https://nextjs.org/docs/advanced-features/custom-server); However, that is not a case for  my web app.

Is there any way to use `envkey` just like a shell command. Something like this:

```
package.json
{
  "scripts": {
    "dev": "envkey next dev",
  }
}
```

**Comment by danenania** [comment]
Hey @vespaiach,  

Sorry about the very slow reply on this. If it's still something you need (or in case someone else finds this), check out [envkey-source](https://github.com/envkey/envkey-source) for loading EnvKey vars at the shell level.
