### ISSUE TITLE
Incompatible with arm64 Linux EC2 instances

### ISSUE THREAD

**Issue by tmrclark** [envkey/envkey-node#28]
Using this library on a linux EC2 instance that uses the AWS [Graviton2 processor](https://aws.amazon.com/ec2/graviton/), which uses an arm64 architecture, results in the following error

```
 Error: spawnSync /var/app/current/node_modules/envkey/ext/envkey-fetch_1.2.9_linux_arm64/envkey-fetch ENOENT
```

The `fetch` function in `loader.js` builds a directory name that does not exist. Are you able to add this binary to the package? Or can `loader.js` be updated to point to a binary that can be run on an linux arm64 machine?

Thank you!

**Comment by danenania** [comment]
Thanks for the bug report @timclark97. Fixed in 1.3.2
