### ISSUE TITLE
Feature/Patch/Consideration: Custom dotEnvFile...

### ISSUE THREAD

**Issue by luncht1me** [envkey/envkey-node#4]
Was trying to pass in custom dotEnvFile and it doesn't work how the current index.js calls loader's load function.

I did a dirty little patch (with README updates) https://github.com/luncht1me/envkey-node/tree/dotEnvKey-options to solve this. 

Reason for the change, is in our development stack at work, we have a lot of production scripts that we run, such as deploying from our local machine to the servers, or scripts to modify production databases ahead of a patch, etc etc. Traditionally, what we've done, is our server has configurations for development, and staging / production NODE_ENVs (using loopback). So, we'd simply change our NODE_ENV (or have a gulp task change it) to run our deployments / update scripts.

Adopting EnvKey (which is GREAT btw) has interrupted this flow, since now all the configurations were loaded from the ENVKEY in the .env file. To prevent having to swap the key out in the file to deploy every time, then switching back to the dev key, noticed there's the ability to add a `dotEnvKey` property to an options object. Great! Only thing is, the current importing doesn't allow you to do this at all.

If you check the commit for changes https://github.com/luncht1me/envkey-node/commit/d5e4bb440bb322e893bf5b8723fc4970603a8db4 you'll see they're very minor. But now, an options object can be passed in while requiring envkey-node. Only problem really, is I think this breaks ES6+ importing. Because of this reason, I'm not doing a pull request but just bringing this use case - which I'm sure we won't be the only people to need the ability to swap out env configs on the fly - to your attention to review, and implement how seen fit. Perhaps if loader.js's load function returned a function that accepted options or something instead, then ES6+ importing can work. Sorry, was in a hurry so didn't explore a better way to fix my situation.

Cheers

**Comment by danenania** [comment]
Hi there! This can actually already be accomplished by importing/requiring the loader directly instead of the top-level module:

```javascript
const envkeyLoader = require('envkey/loader')

envkeyLoader.load({
  dotEnvFile: ".staging.env"
})
```

Or with imports:

```javascript
import {load as envkeyLoad} from 'envkey/loader'

envkeyLoad({
  dotEnvFile: ".staging.env"
})
```

I'll add an example of this to the README. Thanks!

**Comment by luncht1me** [comment]
Thankyou! I was having a hard time figuring out how to accomplish it. Like I said was in a rush :P
