### ISSUE TITLE
Add additional logging when envkey cannot fetch

### ISSUE THREAD

**Issue by noqcks** [envkey/envkey-node#7]
Ran into a problem today where we were running envkey on an Alpine docker container and there was an SSL error when calling AWS because the package `ca-certificates` was not installed on the Alpine container. 

In order to debug I had to add a console.log() of `var res = execFileSync(filePath, execArgs).toString()` in order to see what was happening. 

It would be nice if there was additional logging of some kind here imo 

Logging the execFileSync output for me resulted in the below, allowing me to find the root of the issue. 
```
/tmp # node test.js
/tmp/node_modules/envkey/ext/envkey-fetch_1.1.0_linux_amd64/envkey-fetch
error: Get https://s3-eu-west-1.amazonaws.com/envkey-backup/envs/v1/[REDACTED]: x509: failed to load system roots and no roots provided
```

**Comment by danenania** [comment]
Agreed on logging. That latest update should have improved this, but I'll run some tests on Alpine to make sure.

I'm also going to see if there's a way around requiring the `ca-certificates` dependency. Otherwise, will document this in all the libs. Thanks!

**Comment by danenania** [comment]
@noqcks the latest release (1.1.4) should have improved this on both fronts - envkey-fetch now passes through a specific error message on failure, and a set of trusted root certs (via https://github.com/certifi/gocertifi) are now bundled in envkey-fetch as a backup for when they aren't found in the os. So now the ca-certificates dependency should no longer be needed on Alpine.

**Comment by noqcks** [comment]
awesome! thanks dane!
