### ISSUE TITLE
Serverless-plugin-optimize breaking envkey

### ISSUE THREAD

**Issue by kvarela** [envkey/envkey-node#8]
This probably has nothing to do with Envkey, but I'm at a loss and hope you guys know something.

Basically, my serverless (Lambda) function was working fine with envkey (setting an ENV var for ENVKEY in the lambda function config). Then, my lambda bundle size got too big, so I had to start using [serverless-plugin-optimize](https://github.com/FidelLimited/serverless-plugin-optimize) in order to shrink the bundle size so that I could upload it to AWS.

It works locally, but for some reason, after switching to serverless-plugin-optimize, it says my ENVKEY is invalid:
```TypeError: Cannot create property 'stack' on string 'ENVKEY invalid. Couldn't load vars.'```

My ENVKEY is definitely valid as I've tested the same key locally and it works.

Any ideas?

**Comment by danenania** [comment]
Hmm, you're getting that error at runtime I presume? (Not during the compilation of the bundle?)

Can you check that process.env.ENVKEY has the correct value at the point that you import/require envkey?

**Comment by danenania** [comment]
Skimming through the docs for the plugin, it also looks like it tries to compress included modules as well - I wonder if it might be stripping out the `ext` folder (which contains the envkey-fetch binary envkey needs to run). It looks like there are options to exclude/ignore modules, so perhaps that would help.

**Comment by kvarela** [comment]
Thanks Dane, yea I will try that next. The error is at runtime and I've verified that process.env.ENVKEY has the correct value.

**Comment by danenania** [comment]
Any luck @kvarela?

**Comment by NicolasRitouet** [comment]
@danenania @kvarela I have the same issue, but I'm not using `serverless-plugin-optimize`.
`my process.env.ENVKEY` seems to be correct. It works locally.

**Comment by danenania** [comment]
Hi @NicolasRitouet, can you verify that you can ping https://env.envkey.com/health from inside your function? I'm wondering if it might be a permissions issue for outgoing http requests.

**Comment by danenania** [comment]
Also, I'm working on an update that will provide more specific error messages in these cases--that should help for pinning this down.

**Comment by danenania** [comment]
@NicolasRitouet @kvarela just released 1.1.4 which includes better error handling/more specific error messages, so we should now be able to get a better sense of what's going wrong. 

Also, it's probably a long shot, but 1.1.4 also includes bundled trusted root certificates in envkey-fetch. The lack of these caused problems on Alpine linux, so it's possible that the Lambda runtime is missing these root certs as well and that's what caused the issue. If that's the problem, this update should fix it.

Please let me know either way - thanks!

**Comment by NicolasRitouet** [comment]
@danenania The error message helped, here's what I got:
`fetch error: Get https://env.envkey.com/v1/TOKENREPLACED?clientName=envkey-node&clientVersion=1.1.4&clientOs=linux&clientArch=amd64: dial tcp 35.171.200.197:443: i/o timeout`  
and  
`backup fetch error: Get https://s3-eu-west-1.amazonaws.com/envkey-backup/envs/v1/TOKENALSOREPLACED: dial tcp 52.218.104.186:443: i/o timeout`
it seems to be an issue with my NAT gateway (lambda is in a vpc)
Thanks for your support 👍

**Comment by danenania** [comment]
Sure thing! If you figure out the right approach with the NAT gateway, could you describe it here? Some other users have run into this as well with Lambda, so I'd like to add some notes to the docs.

**Comment by NicolasRitouet** [comment]
@danenania well, if you're using a VPC with a lambda, you have to use a NAT gateway to access internet (and therefore enkey api), the documentation is here: https://aws.amazon.com/premiumsupport/knowledge-center/internet-access-lambda-function/
I hope it helps :)
